# Site settings
title: Jay Prakash
description: Jekyll Theme Minimal Resume
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://drdjango.ml" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jay Prakash
user_description: I\'m a Jay Prakash Persuing my B.Tech from National Institute of Technology Raipur, always searching for the next challenge; no task is too scary nor too difficult. I am fond of devlopment in various tech stacks and frameworks from <b>Web, Cloud, Edge Devices</b> etc.
user_title: Django Developer
email: unijay12@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
